### ISSUE TITLE
Use Theme-Change for both Light/Dark/OS and Theme Color?

### ISSUE THREAD

**Issue by Merovex** [saadeghi/theme-change#39]
Is there a straightforward way to use Theme Change to pull double duty? I have it selecting themes without issue. But, I want the user to select the color theme, and the Day/Night theme (light,dark,OS). (I'm also using DaisyUI.) Sorry for the softball question.

**Comment by saadeghi** [comment]
I'm not sure if I understand correctly but there is no difference between "Day/Night theme" and "color theme". It's just theme.  
In CSS we can apply specific style for dark mode using `@media (prefers-color-scheme: dark)` and it only works if OS or browser is set to dark mode. it won't apply otherwise. The value comes from browser and  as far as I know we can't overwrite it using JS (force using `prefers-color-scheme: dark` when the OS/browser is not set to dark mode).

What we can do using CSS is setting a specific theme when `prefers-color-scheme` is dark (using `@media (prefers-color-scheme: dark)` media query) and what we can do using JS is add/remove a specific attribute (like `data-theme`) or a class name to `<html>` (or other tags) so a specific style (`[data-theme=themeName] { /* any style */ }`) gets applied.

In CSS you can do something like this to have 2 shades of color for one theme. let's say the theme is named `mytheme` and it has both dark and light media queries so it adapts OS settings.
```css
[data-theme=mytheme]{
  background: white;
  color: black;
}
@media (prefers-color-scheme: dark) {
  [data-theme=mytheme]{
    background: black;
    color: white;
  }
}
```
And in this case you don't even need JS to switch it (you can't - as far as I know).  
If you have 2 themes like this (actually 4 themes), you would need a CSS like this:

```css
[data-theme=theme1]{
  background: white;
  color: black;
}
[data-theme=theme2]{
  background: skyblue;
  color: darkblue;
}
@media (prefers-color-scheme: dark) {
  [data-theme=theme1]{
    background: black;
    color: white;
  }
  [data-theme=theme2]{
    background: darkblue;
    color: skyblue;
  }
}
```
But I don't really think there's a use case for that. I mean... user might want to pick a theme. dark theme or light theme is not a concept. it's just color. and colors can be dark or light.  
And if someone wants to go this road, there's no limit how many dimension we can use as "themes" we can consider dark/light theme a theme concept, the brand colors as a second theme concept, the border radius of element a third theme concept, etc.
